version: "3.9"

services:
    app:               # PHP-FPM + Composer + Node (para npm install do Laravel Mix, se precisar)
        build: ./docker/php
        volumes:
            - ./backend:/var/www/html
        environment:
            APP_ENV: local
            DB_HOST: db
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: secret
        depends_on:
            - db

    web:               # nginx servindo Laravel
        image: nginx:alpine
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app

    front:
        build: ./frontend
        command: "npm install && npm run start"
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"
        depends_on:
            - app

    db:
        image: mysql:8.4
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data:
